defmodule Wymcp.Methods.ToolsCallTest do
  use ExUnit.Case, async: true

  @moduledoc """
  Tests for the Wymcp.Methods.ToolsCall handler.

  ToolsCall is the most complex method handler. It must:
  1. Validate that `params.name` is a string and `params.arguments` is a map
  2. Look up the tool by name from the registered tools list
  3. Validate the arguments against the tool's oneOf JSON Schema
  4. Call the tool's run/2 (generated by `use Wymcp.Tool`) on success
  5. Return JSON-RPC error responses for unknown tools or invalid params

  If a tool's `run/2` raises, the exception is caught and a JSON-RPC
  internal error (-32603) is returned instead of crashing the request.

  Tool-level errors (isError: true in the result) are distinct from protocol-level
  errors (JSON-RPC error codes). A tool returning `{:error, reason}` from
  `run_action/2` produces a successful JSON-RPC response with an error result.
  """

  import Plug.Test
  import Plug.Conn

  alias Wymcp.Methods.ToolsCall
  alias Wymcp.Session

  defmodule EchoTool do
    use Wymcp.Tool

    def name, do: "echo"
    def description, do: "Echoes input"

    def actions do
      %{
        echo: %{
          description: "Echo text back",
          properties: %{"text" => %{"type" => "string"}},
          required: ["text"],
          defaults: %{}
        }
      }
    end

    def run_action(:echo, %{"text" => text}, _ctx), do: {:ok, %{echoed: text}}
  end

  defmodule AssignsTool do
    @moduledoc false
    use Wymcp.Tool

    def name, do: "assigns_reader"
    def description, do: "Reads from ctx.assigns"

    def actions do
      %{
        read: %{
          description: "Returns assigns",
          properties: %{},
          required: [],
          defaults: %{}
        }
      }
    end

    def run_action(:read, _data, ctx) do
      {:ok, %{scope: ctx.assigns[:current_scope], internal: ctx.assigns[:wymcp_internal_flag]}}
    end
  end

  defmodule CrashingTool do
    use Wymcp.Tool

    def name, do: "crasher"
    def description, do: "Always raises"

    def actions do
      %{
        crash: %{
          description: "Raises an error",
          properties: %{},
          required: [],
          defaults: %{}
        }
      }
    end

    def run_action(:crash, _data, _ctx), do: raise("boom")
  end

  defp build_conn(method, params, tools \\ []) do
    body = %{"jsonrpc" => "2.0", "id" => 1, "method" => method, "params" => params}

    {:ok, pid, session_id} =
      Session.start_session(%{
        client_capabilities: %{},
        client_info: %{"name" => "test", "version" => "1.0"},
        protocol_version: "2025-11-25",
        tools: tools,
        auth: nil
      })

    Session.mark_ready(pid)

    conn(:post, "/")
    |> put_req_header("content-type", "application/json")
    |> Map.put(:body_params, body)
    |> assign(:wymcp_session_pid, pid)
    |> assign(:wymcp_session_id, session_id)
  end

  test "calls the matching tool and returns its response" do
    conn =
      build_conn(
        "tools/call",
        %{
          "name" => "echo",
          "arguments" => %{"action" => "echo", "data" => %{"text" => "hello"}}
        },
        [EchoTool]
      )

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["result"]["isError"] == false
    content = body["result"]["content"] |> hd() |> Map.get("text") |> JSON.decode!()
    assert content["echoed"] == "hello"
  end

  test "returns method_not_found for unknown tool" do
    conn = build_conn("tools/call", %{"name" => "nope", "arguments" => %{}}, [EchoTool])
    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32601
  end

  test "returns invalid_params for schema-violating arguments" do
    conn =
      build_conn(
        "tools/call",
        %{
          "name" => "echo",
          "arguments" => %{"not_action" => "bad"}
        },
        [EchoTool]
      )

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32602
  end

  @tag capture_log: true
  test "returns internal_error when tool raises" do
    conn =
      build_conn(
        "tools/call",
        %{
          "name" => "crasher",
          "arguments" => %{"action" => "crash"}
        },
        [CrashingTool]
      )

    result = ToolsCall.run(conn, [CrashingTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32603
    assert body["error"]["message"] =~ "Internal error"
  end

  test "returns invalid_params when name is missing" do
    conn =
      build_conn("tools/call", %{"arguments" => %{}}, [EchoTool])

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32602
  end

  test "returns invalid_params when arguments is missing" do
    conn =
      build_conn("tools/call", %{"name" => "echo"}, [EchoTool])

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32602
  end

  @tag doc: """
       help and describe bypass schema validation so they work in full mode
       without being injected into the oneOf schema. A failure means full-mode
       tools lose self-documentation.
       """
  test "help action bypasses schema validation" do
    conn =
      build_conn(
        "tools/call",
        %{
          "name" => "echo",
          "arguments" => %{"action" => "help"}
        },
        [EchoTool]
      )

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["result"]["isError"] == false
  end

  test "describe action bypasses schema validation" do
    conn =
      build_conn(
        "tools/call",
        %{
          "name" => "echo",
          "arguments" => %{"action" => "describe", "data" => %{"topic" => "echo"}}
        },
        [EchoTool]
      )

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["result"]["isError"] == false
  end

  test "returns invalid_params when params is empty" do
    conn =
      build_conn("tools/call", %{}, [EchoTool])

    result = ToolsCall.run(conn, [EchoTool])
    body = JSON.decode!(result.resp_body)

    assert body["error"]["code"] == -32602
  end

  describe "conn.assigns bridge" do
    @tag doc: """
         Per-request conn.assigns set by upstream plugs (like auth) must be
         visible in ctx.assigns so tools can read them without process dictionary
         hacks. Internal wymcp keys must be filtered out to avoid leaking
         framework plumbing.
         """
    test "conn.assigns are visible in ctx.assigns" do
      conn =
        build_conn(
          "tools/call",
          %{
            "name" => "assigns_reader",
            "arguments" => %{"action" => "read"}
          },
          [AssignsTool]
        )

      conn = Plug.Conn.assign(conn, :current_scope, %{user: "alice"})
      conn = ToolsCall.run(conn, [AssignsTool])

      body = JSON.decode!(conn.resp_body)
      content = hd(body["result"]["content"])["text"] |> JSON.decode!()
      assert content["scope"] == %{"user" => "alice"}
    end

    test "wymcp internal assigns are filtered out" do
      conn =
        build_conn(
          "tools/call",
          %{
            "name" => "assigns_reader",
            "arguments" => %{"action" => "read"}
          },
          [AssignsTool]
        )

      conn = Plug.Conn.assign(conn, :current_scope, %{user: "alice"})
      conn = Plug.Conn.assign(conn, :wymcp_internal_flag, true)
      conn = ToolsCall.run(conn, [AssignsTool])

      body = JSON.decode!(conn.resp_body)
      content = hd(body["result"]["content"])["text"] |> JSON.decode!()
      assert content["internal"] == nil
    end

    @tag doc: """
         Session assigns take precedence over conn.assigns. This ensures that
         accumulated tool state (counters, cached lookups) is not overwritten
         by plug defaults. conn.assigns provide the base layer.
         """
    test "session assigns take precedence over conn.assigns" do
      {:ok, pid, _id} =
        Wymcp.Session.start_session(%{
          client_capabilities: %{},
          client_info: %{"name" => "test", "version" => "1.0"},
          protocol_version: "2025-11-25",
          tools: [AssignsTool],
          auth: nil,
          server: nil
        })

      Wymcp.Session.mark_ready(pid)
      Wymcp.Session.put_assigns(pid, %{current_scope: %{user: "from_session"}})
      session_id = Wymcp.Session.get_state(pid).session_id

      conn =
        build_conn("tools/call", %{
          "name" => "assigns_reader",
          "arguments" => %{"action" => "read"}
        })

      conn = Plug.Conn.assign(conn, :current_scope, %{user: "from_conn"})
      conn = Plug.Conn.assign(conn, :wymcp_session_pid, pid)
      conn = Plug.Conn.assign(conn, :wymcp_session_id, session_id)
      conn = ToolsCall.run(conn, [AssignsTool])

      body = JSON.decode!(conn.resp_body)
      content = hd(body["result"]["content"])["text"] |> JSON.decode!()
      # Session value wins over conn value
      assert content["scope"] == %{"user" => "from_session"}
    end
  end
end
